WIP: Added Meals
HackAssistant/hackassistant pull request #55
Opened 2022-10-30 17:30 UTC by EncryptEx

## Patch Notes

## Which issue(s) this PR fixes (optional) 

Fixes #
References #

## Additional Notes (optional)

## Some questions
- [x] I have read the contributing guidelines
- [x] I abide by this repository Code of Conduct
- [x] I understand that my PR won't be merged until GitHub gives a "green light"

2022-10-30 17:32 UTC, EncryptEx commented
Updated branch ^^

2022-12-12 17:08 UTC, Casassarnau requested changes

2022-12-12 18:55 UTC, EncryptEx commented on event/meals/views.py
> +        return JsonResponse({'success': 'Something went wrong, please contact an administrator'})
true, line'll be removed

2022-12-15 23:18 UTC, Casassarnau approved these changes
LGTM

2022-12-15 23:19 UTC, merged